const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/../neca.html','utf8');
const js=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(js);
const nodes={},mem={};
function node(id){return nodes[id]??={innerHTML:'',value:'',checked:false,addEventListener(){},dispatchEvent(){},querySelectorAll(){return []},classList:{toggle(){}},appendChild(){}}}
const ctx=vm.createContext({console,Event:class{},localStorage:{getItem:k=>mem[k]||null,setItem:(k,v)=>mem[k]=v},document:{querySelector:node,querySelectorAll:()=>[],getElementById:id=>nodes['#'+id]||null,createElement:()=>({innerHTML:'',get textContent(){return this.innerHTML.replace(/<[^>]+>/g,' ')}})},location:{hash:'#home'},window:{scrollY:0,scrollTo(){}},requestAnimationFrame:f=>f(),setTimeout:()=>1,clearTimeout(){}});
const run=s=>vm.runInContext(s,ctx);
run(js.slice(0,js.indexOf("document.addEventListener('click'")));
let n=0;const check=(title,f)=>{f();n++;console.log('PASS '+title)};
check('all IDs retained',()=>{for(const [k,prefix,n] of [['cards','c',30],['questions','q',42],['experiences','e',10]]){const ids=JSON.parse(run(`JSON.stringify(DATA.${k}.map(x=>x.id))`));assert.equal(ids.length,n);for(let i=1;i<=n;i++)assert(ids.includes(prefix+i))}});
run(`state.notes={q2:'나의 지원동기\\n둘째 줄 <script>',e3:'CP 경험 메모'};practice()`);
check('default practice hides only strategy',()=>assert.equal((nodes['#questions'].innerHTML.match(/<details id="q/g)||[]).length,41));
check('next question and related links',()=>assert(nodes['#questions'].innerHTML.includes('다음 필수 질문')&&nodes['#questions'].innerHTML.includes('비슷한 질문')));
check('uniform badges removed',()=>assert(!nodes['#questions'].innerHTML.includes('연습 가능')));
check('saved answer editable',()=>assert(nodes['#questions'].innerHTML.includes('나의 지원동기')));
run('experience()');check('experience cards precede supporting map',()=>assert(nodes['#view'].innerHTML.indexOf('x-e7')<nodes['#view'].innerHTML.indexOf('내 경험을 NECA 언어로 보기')));
run('summary()');check('summary includes personal answer and experience safely',()=>assert(nodes['#view'].innerHTML.includes('나의 지원동기')&&nodes['#view'].innerHTML.includes('CP 경험 메모')&&nodes['#view'].innerHTML.includes('&lt;script&gt;')));
check('body used in search',()=>assert(run(`searchText(DATA.cards.find(c=>c.id==='c26')).includes('위촉')`)));
check('no duplicate search text',()=>assert(run(`DATA.cards.every(c=>!('text' in c))`)));
check('interest not predetermined',()=>assert(run(`DATA.questions.find(q=>q.id==='q38').answer.includes('정해두지는 않았습니다')`)));
run('home()');check('home renders next action',()=>assert(nodes['#view'].innerHTML.includes('답변 연습하기')));
run(`state.practiced=DATA.questions.filter(q=>q.group!=='준비 전략').map(q=>q.id);home()`);check('finished practice shows review',()=>assert(nodes['#view'].innerHTML.includes('모든 질문을 한 번씩 연습했습니다')));
node('#search').value='위촉';node('#group').value='기관과 제도';node('#only-review').checked=true;
run("activeRoute='learn';rememberView()");node('#search').value='';node('#group').value='';node('#only-review').checked=false;
run("restoreView('learn',null)");check('route filters restored',()=>assert(nodes['#search'].value==='위촉'&&nodes['#group'].value==='기관과 제도'&&nodes['#only-review'].checked));
run(`state.practiced=[];state.done=[];state.review=[];state.notes={q1:'기존 메모'};state.last='c1';localStorage.setItem(BASE_KEY,JSON.stringify(state));let remote={...state,done:['c1'],notes:{q1:'기존 메모'}};state.review=['c2'];let release,payload;syncCfg=()=>({gistId:'test'});showSync=()=>{};refresh=()=>{};syncSoon=()=>{};gh=(c,path,opt)=>{if(!opt)return Promise.resolve({files:{[SYNC_FILE]:{content:JSON.stringify(remote)}}});payload=JSON.parse(JSON.parse(opt.body).files[SYNC_FILE].content);return new Promise(r=>release=()=>{remote=payload;r({})})}`);
(async()=>{let p=run('syncNow()');await new Promise(r=>setImmediate(r));run(`state.notes.q1='전송 중 새 메모';release()`);await p;check('base is transmitted snapshot',()=>assert.equal(run('JSON.parse(localStorage.getItem(BASE_KEY)).notes.q1'),'기존 메모'));p=run('syncNow()');await new Promise(r=>setImmediate(r));check('next sync preserves new input',()=>assert.equal(run('state.notes.q1'),'전송 중 새 메모'));run('release()');await p;check('new input reaches remote',()=>assert.equal(run('remote.notes.q1'),'전송 중 새 메모'));console.log(n+' checks passed')})().catch(e=>{console.error(e);process.exitCode=1});
